entrypoint: "gunicorn -b :$PORT app:app"
env: flex
runtime: custom
runtime_config: 
  python_version: 3.7

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 7    
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10